
USE CompanyDB;
GO

-- 1 EMP 

CREATE TABLE EMP (
    SSN VARCHAR(11) PRIMARY KEY,
    Fname VARCHAR(50),
    Lname VARCHAR(50),
    Gender CHAR(1) CHECK (Gender IN ('M', 'F')),
    super_id VARCHAR(11),
    BD DATE NOT NULL,
    DUNM INT
);
GO

-- 2 DEPT 

CREATE TABLE DEPT (
    DUNM INT PRIMARY KEY,
    SSN VARCHAR(11),
    HIRDATE DATE NOT NULL,
    DN VARCHAR(100),
    FOREIGN KEY (SSN) REFERENCES EMP(SSN)
);
GO

-- Adding DEPT foreign key to EMP
ALTER TABLE EMP
ADD FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM);
GO

-- Adding recursive FK for EMP
ALTER TABLE EMP
ADD FOREIGN KEY (super_id) REFERENCES EMP(SSN);
GO

-- 3 LOC

CREATE TABLE LOC (
    DUNM INT,
    LOC VARCHAR(100),
    PRIMARY KEY (DUNM, LOC),
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);
GO

-- 4 PROJECT
CREATE TABLE PROJECT (
    PNUM INT PRIMARY KEY,
    PN VARCHAR(100),
    LOC VARCHAR(100),
    CITY VARCHAR(100),
    DUNM INT,
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);
GO

-- 5 WORK

CREATE TABLE WORK (
    SSN VARCHAR(11),
    PNUM INT,
    hours INT CHECK (hours >= 0),
    PRIMARY KEY (SSN, PNUM),
    FOREIGN KEY (SSN) REFERENCES EMP(SSN),
    FOREIGN KEY (PNUM) REFERENCES PROJECT(PNUM)
);
GO

-- 6 dependent

CREATE TABLE dependent (
    ssn VARCHAR(11),
    dnum VARCHAR(50),
    BD DATE,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    PRIMARY KEY (ssn, dnum),
    FOREIGN KEY (ssn) REFERENCES EMP(SSN)
);
GO
